export const LOGIN_ACCOUNT = 'LOGGING_ACCTOUNT';
export const LOGIN_ACCOUNT_SUCCESS = 'LOGGING_ACCOUNT_SUCCESS';
export const LOGIN_ACCOUNT_FAILED = 'LOGGING_ACCOUNT_FAILED';
export const GET_USERNAME = "GET_USERNAME";
export const LOG_OUT = 'LOG_OUT';

export const REGISTER_ACCOUNT = 'REGISTER_ACCOUNT';
export const REGISTER_ACCOUNT_SUCCESSFULL = 'REGISTER_ACCOUNT_SUCCESSFUL';
export const REGISTER_ACCOUNT_FAILED = 'REGISTER_ACCOUNT_FAILED';

export const GET_CATEGORY = "GET_CATEGORY";
export const GET_RANDOM_CATEGORY = "GET_RANDOM_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORY_FAILED = 'GET_CATEGORY_FAILED';

export const GET_PRODUCT = "GET_PRODUCT";
export const GET_RANDOM_PRODUCT = "GET_RANDOM_PRODUCT";
export const GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED';
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_BY_CATEGORY = 'GET_PRODUCTS_BY_CATEGORY';

export const GET_ITEM = "GET_ITEM ";
export const GET_ITEMS  = "GET_RANDOM_ITEM ";
export const GET_ITEM_FAILED = 'GET_ITEM _FAILED';
export const GET_ITEMS_BY_PRODUCT = "GET_ITEMS_BY_PRODUCT";
export const GET_RANDOM_ITEMS = "GET_RANDOM_ITEMS";

export const GET_REVIEW = "GET_REVIEW";
export const GET_REVIEWS_BY_ITEM  = "GET_REVIEWS_BY_ITEM";
export const GET_REVIEWS_BY_USER = "GET_REVIEWS_BY_USER";
export const GET_REVIEW_FAILED = 'GET_REVIEW_FAILED';
export const SEND_REVIEW = "SEND_REVIEW";
